/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ModId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Game = IDL.Text;
export const Tag = IDL.Text;
export const ModInput = IDL.Record({
  'title' : IDL.Text,
  'game' : Game,
  'scriptText' : IDL.Text,
  'tags' : IDL.Vec(Tag),
  'description' : IDL.Text,
  'configJson' : IDL.Text,
  'isPublic' : IDL.Bool,
});
export const Mod = IDL.Record({
  'id' : ModId,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'modifiedAt' : IDL.Int,
  'game' : Game,
  'scriptText' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(Tag),
  'description' : IDL.Text,
  'configJson' : IDL.Text,
  'isEnabled' : IDL.Bool,
  'isPublic' : IDL.Bool,
  'attachments' : IDL.Vec(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'characterName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Opt(IDL.Text),
  'photoUrl' : IDL.Opt(IDL.Text),
  'backstory' : IDL.Opt(IDL.Text),
  'abilities' : IDL.Opt(IDL.Text),
});
export const ModUpdate = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'game' : IDL.Opt(Game),
  'scriptText' : IDL.Opt(IDL.Text),
  'tags' : IDL.Opt(IDL.Vec(Tag)),
  'description' : IDL.Opt(IDL.Text),
  'configJson' : IDL.Opt(IDL.Text),
  'isPublic' : IDL.Opt(IDL.Bool),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addModAttachment' : IDL.Func([ModId, ExternalBlob], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMod' : IDL.Func([ModInput], [ModId], []),
  'deleteMod' : IDL.Func([ModId], [], []),
  'getAllMods' : IDL.Func([], [IDL.Vec(Mod)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDownloadInfo' : IDL.Func(
      [ModId],
      [IDL.Record({ 'mod' : Mod, 'attachments' : IDL.Vec(ExternalBlob) })],
      ['query'],
    ),
  'getMod' : IDL.Func([ModId], [IDL.Opt(Mod)], ['query']),
  'getModAttachments' : IDL.Func([ModId], [IDL.Vec(ExternalBlob)], ['query']),
  'getModStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'publicMods' : IDL.Nat,
          'totalMods' : IDL.Nat,
          'totalTags' : IDL.Nat,
          'totalGames' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getModsByGame' : IDL.Func([Game], [IDL.Vec(Mod)], ['query']),
  'getModsByTag' : IDL.Func([Tag], [IDL.Vec(Mod)], ['query']),
  'getMyModIds' : IDL.Func([], [IDL.Vec(ModId)], ['query']),
  'getPopularGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getPopularTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyMods' : IDL.Func([], [IDL.Vec(Mod)], ['query']),
  'listPublicMods' : IDL.Func([], [IDL.Vec(Mod)], ['query']),
  'removeModAttachment' : IDL.Func([ModId, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchMods' : IDL.Func([IDL.Text], [IDL.Vec(Mod)], ['query']),
  'toggleModEnabled' : IDL.Func([ModId], [IDL.Bool], []),
  'updateMod' : IDL.Func([ModId, ModUpdate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ModId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Game = IDL.Text;
  const Tag = IDL.Text;
  const ModInput = IDL.Record({
    'title' : IDL.Text,
    'game' : Game,
    'scriptText' : IDL.Text,
    'tags' : IDL.Vec(Tag),
    'description' : IDL.Text,
    'configJson' : IDL.Text,
    'isPublic' : IDL.Bool,
  });
  const Mod = IDL.Record({
    'id' : ModId,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'modifiedAt' : IDL.Int,
    'game' : Game,
    'scriptText' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(Tag),
    'description' : IDL.Text,
    'configJson' : IDL.Text,
    'isEnabled' : IDL.Bool,
    'isPublic' : IDL.Bool,
    'attachments' : IDL.Vec(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'characterName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Opt(IDL.Text),
    'photoUrl' : IDL.Opt(IDL.Text),
    'backstory' : IDL.Opt(IDL.Text),
    'abilities' : IDL.Opt(IDL.Text),
  });
  const ModUpdate = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'game' : IDL.Opt(Game),
    'scriptText' : IDL.Opt(IDL.Text),
    'tags' : IDL.Opt(IDL.Vec(Tag)),
    'description' : IDL.Opt(IDL.Text),
    'configJson' : IDL.Opt(IDL.Text),
    'isPublic' : IDL.Opt(IDL.Bool),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addModAttachment' : IDL.Func([ModId, ExternalBlob], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMod' : IDL.Func([ModInput], [ModId], []),
    'deleteMod' : IDL.Func([ModId], [], []),
    'getAllMods' : IDL.Func([], [IDL.Vec(Mod)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDownloadInfo' : IDL.Func(
        [ModId],
        [IDL.Record({ 'mod' : Mod, 'attachments' : IDL.Vec(ExternalBlob) })],
        ['query'],
      ),
    'getMod' : IDL.Func([ModId], [IDL.Opt(Mod)], ['query']),
    'getModAttachments' : IDL.Func([ModId], [IDL.Vec(ExternalBlob)], ['query']),
    'getModStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'publicMods' : IDL.Nat,
            'totalMods' : IDL.Nat,
            'totalTags' : IDL.Nat,
            'totalGames' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getModsByGame' : IDL.Func([Game], [IDL.Vec(Mod)], ['query']),
    'getModsByTag' : IDL.Func([Tag], [IDL.Vec(Mod)], ['query']),
    'getMyModIds' : IDL.Func([], [IDL.Vec(ModId)], ['query']),
    'getPopularGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getPopularTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyMods' : IDL.Func([], [IDL.Vec(Mod)], ['query']),
    'listPublicMods' : IDL.Func([], [IDL.Vec(Mod)], ['query']),
    'removeModAttachment' : IDL.Func([ModId, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchMods' : IDL.Func([IDL.Text], [IDL.Vec(Mod)], ['query']),
    'toggleModEnabled' : IDL.Func([ModId], [IDL.Bool], []),
    'updateMod' : IDL.Func([ModId, ModUpdate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };