/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type Game = string;
export interface Mod {
  'id' : ModId,
  'title' : string,
  'owner' : Principal,
  'modifiedAt' : bigint,
  'game' : Game,
  'scriptText' : string,
  'createdAt' : bigint,
  'tags' : Array<Tag>,
  'description' : string,
  'configJson' : string,
  'isEnabled' : boolean,
  'isPublic' : boolean,
  'attachments' : Array<ExternalBlob>,
}
export type ModId = bigint;
export interface ModInput {
  'title' : string,
  'game' : Game,
  'scriptText' : string,
  'tags' : Array<Tag>,
  'description' : string,
  'configJson' : string,
  'isPublic' : boolean,
}
export interface ModUpdate {
  'title' : [] | [string],
  'game' : [] | [Game],
  'scriptText' : [] | [string],
  'tags' : [] | [Array<Tag>],
  'description' : [] | [string],
  'configJson' : [] | [string],
  'isPublic' : [] | [boolean],
}
export type Tag = string;
export interface UserProfile {
  'characterName' : [] | [string],
  'name' : string,
  'role' : [] | [string],
  'photoUrl' : [] | [string],
  'backstory' : [] | [string],
  'abilities' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addModAttachment' : ActorMethod<[ModId, ExternalBlob], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMod' : ActorMethod<[ModInput], ModId>,
  'deleteMod' : ActorMethod<[ModId], undefined>,
  'getAllMods' : ActorMethod<[], Array<Mod>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDownloadInfo' : ActorMethod<
    [ModId],
    { 'mod' : Mod, 'attachments' : Array<ExternalBlob> }
  >,
  'getMod' : ActorMethod<[ModId], [] | [Mod]>,
  'getModAttachments' : ActorMethod<[ModId], Array<ExternalBlob>>,
  'getModStats' : ActorMethod<
    [],
    {
      'publicMods' : bigint,
      'totalMods' : bigint,
      'totalTags' : bigint,
      'totalGames' : bigint,
    }
  >,
  'getModsByGame' : ActorMethod<[Game], Array<Mod>>,
  'getModsByTag' : ActorMethod<[Tag], Array<Mod>>,
  'getMyModIds' : ActorMethod<[], Array<ModId>>,
  'getPopularGames' : ActorMethod<[], Array<Game>>,
  'getPopularTags' : ActorMethod<[], Array<Tag>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyMods' : ActorMethod<[], Array<Mod>>,
  'listPublicMods' : ActorMethod<[], Array<Mod>>,
  'removeModAttachment' : ActorMethod<[ModId, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchMods' : ActorMethod<[string], Array<Mod>>,
  'toggleModEnabled' : ActorMethod<[ModId], boolean>,
  'updateMod' : ActorMethod<[ModId, ModUpdate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];